language: python
cache: pip
dist: bionic

addons:
  apt:
    packages:
      - sqlite3
      - gdal-bin

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel
  - pip install $DJANGO
  - pip install -U -r requirements-test.txt
  # temporary: remove when openwisp-utils 0.5.0 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa,rest]

install:
  - python setup.py -q develop

before-script:
  - ./run-qa-checks

script:
  - SAMPLE_APP=1 coverage run --source=openwisp_notifications runtests.py
  - coverage run -a --source=openwisp_notifications runtests.py

after_success:
  - coveralls
